CREATE TABLE [dbo].[D001006] (
    [CenterId]          INT        NOT NULL,
    [EffectiveDt]       DATETIME   NOT NULL,
    [LBrCode]           INT        NOT NULL,
    [CenterName]        CHAR (50)  NOT NULL,
    [BrnCenterId]       CHAR (8)   NOT NULL,
    [MaxGroup]          INT        NOT NULL,
    [CurrNoOfGroups]    INT        NOT NULL,
    [MaxGroupMembers]   INT        NOT NULL,
    [Add1]              CHAR (50)  NULL,
    [Add2]              CHAR (50)  NULL,
    [Area]              INT        NOT NULL,
    [Landmark]          CHAR (50)  NOT NULL,
    [CityCd]            CHAR (6)   NOT NULL,
    [StateCd]           CHAR (3)   NOT NULL,
    [CountryCd]         CHAR (3)   NOT NULL,
    [PinCode]           CHAR (10)  NOT NULL,
    [Phone1]            CHAR (15)  NOT NULL,
    [Fax]               CHAR (15)  NOT NULL,
    [FormatnDt]         DATETIME   NOT NULL,
    [MeetingFreq]       CHAR (1)   NOT NULL,
    [UserCode]          CHAR (8)   NOT NULL,
    [MeetingLocn]       CHAR (30)  NOT NULL,
    [CenterLeader]      INT        NOT NULL,
    [Village]           CHAR (50)  NOT NULL,
    [Market]            CHAR (50)  NOT NULL,
    [MeetingDay]        TINYINT    NOT NULL,
    [CenterMtTime]      DATETIME   NOT NULL,
    [CenterMtHHMM]      CHAR (5)   NOT NULL,
    [CenterMtAMPM]      TINYINT    NOT NULL,
    [FirstMeetngDt]     DATETIME   NOT NULL,
    [NextMeetngDt]      DATETIME   NOT NULL,
    [AdhocNextMeetngDt] DATETIME   NOT NULL,
    [LastMeetngDt]      DATETIME   NOT NULL,
    [Latitude]          FLOAT (53) NOT NULL,
    [Longitude]         FLOAT (53) NOT NULL,
    [GroupNoCnt]        INT        NOT NULL,
    [MeetingSchedule]   CHAR (1)   NOT NULL,
    [RepayFrom]         INT        NOT NULL,
    [RepayTo]           INT        NOT NULL,
    [AreaType]          INT        NOT NULL,
    [WardNo]            CHAR (6)   NOT NULL,
    [NoOfMeetingsHeld]  INT        NOT NULL,
    [CRSEffectiveDt]    DATETIME   NOT NULL,
    [CRS]               CHAR (8)   NOT NULL,
    [FeesAmt]           FLOAT (53) NOT NULL,
    [FeesCrAcctId]      CHAR (32)  NOT NULL,
    [ClusterName]       CHAR (20)  NOT NULL,
    [BlockName]         CHAR (20)  NOT NULL,
    [DistFrmHoBranch]   FLOAT (53) NOT NULL,
    [SexCode]           CHAR (2)   NOT NULL,
    [SamityChairman]    INT        NOT NULL,
    [MaxCenterMember]   INT        NOT NULL,
    [CurrNoOfMembers]   INT        NOT NULL,
    [VillageAdd]        INT        NOT NULL,
    [DistCd]            INT        NOT NULL,
    [CenterStatus]      TINYINT    NOT NULL,
    [DropOutDate]       DATETIME   NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [WeekNumber]        TINYINT    NOT NULL,
    [AddInfo1]          CHAR (35)  NOT NULL,
    [AddInfo2]          CHAR (35)  NOT NULL,
    [ChangedtManual]    CHAR (2)   NOT NULL,
    [DistFrmSubPostOff] FLOAT (53) NOT NULL,
    [PostOffCd]         CHAR (6)   NOT NULL,
    [SubPostOffCd]      CHAR (6)   NOT NULL
);

