CREATE TABLE [dbo].[D009122] (
    [LBrCode]          INT       NOT NULL,
    [PrdAcctId]        CHAR (32) NOT NULL,
    [MemberType]       TINYINT   NOT NULL,
    [MemberNo]         INT       NOT NULL,
    [MinBalChgYN]      CHAR (1)  NOT NULL,
    [ChqBookChgYN]     CHAR (1)  NOT NULL,
    [TdsYN]            CHAR (1)  NOT NULL,
    [TdsReasonCd]      SMALLINT  NOT NULL,
    [InspChgsYN]       CHAR (1)  NOT NULL,
    [DematYN]          CHAR (1)  NOT NULL,
    [DematNo]          CHAR (16) NOT NULL,
    [ServiceChgsYN]    CHAR (1)  NOT NULL,
    [AtmYN]            CHAR (1)  NOT NULL,
    [FreqStmtOfAcctYN] CHAR (1)  NOT NULL,
    [LastPrintDt]      DATETIME  NOT NULL,
    [PassBookChgYN]    CHAR (1)  NOT NULL,
    [TrFrAcctYN]       CHAR (1)  NOT NULL,
    [InspecYN]         CHAR (1)  NOT NULL,
    [GraceDp]          TINYINT   NOT NULL,
    [PayInAcctId]      CHAR (32) NOT NULL,
    [BicCode]          SMALLINT  NOT NULL,
    [SicCode]          SMALLINT  NOT NULL,
    [FolioChgsYN]      CHAR (1)  NOT NULL,
    [StmtType]         TINYINT   NOT NULL,
    [InDirRelation]    CHAR (1)  NOT NULL,
    [DirRelation]      TINYINT   NOT NULL,
    [AcNo]             CHAR (20) NOT NULL,
    [BookCurCd]        CHAR (3)  NOT NULL,
    [SubacctYN]        CHAR (1)  NOT NULL,
    [ModuleType]       INT       NOT NULL,
    [EmailDayInFreq]   TINYINT   NOT NULL,
    [MemReasonCd]      SMALLINT  NOT NULL
);

