CREATE TABLE [dbo].[D009511] (
    [CustNo]         INT      NOT NULL,
    [SrNo]           INT      NOT NULL,
    [ModifyDt]       DATETIME NOT NULL,
    [Crs]            CHAR (8) NOT NULL,
    [CenterId]       INT      NOT NULL,
    [GroupCd]        INT      NOT NULL,
    [GrpPrdCd]       CHAR (8) NOT NULL,
    [GrpGender]      CHAR (4) NOT NULL,
    [DbtrAddMk]      INT      NOT NULL,
    [DbtrAddMb]      INT      NOT NULL,
    [DbtrAddMs]      SMALLINT NOT NULL,
    [DbtrAddMd]      DATETIME NOT NULL,
    [DbtrAddMt]      DATETIME NOT NULL,
    [DbtrAddCk]      INT      NOT NULL,
    [DbtrAddCb]      INT      NOT NULL,
    [DbtrAddCs]      SMALLINT NOT NULL,
    [DbtrAddCd]      DATETIME NOT NULL,
    [DbtrAddCt]      DATETIME NOT NULL,
    [DbtrLupdMk]     INT      NOT NULL,
    [DbtrLupdMb]     INT      NOT NULL,
    [DbtrLupdMs]     SMALLINT NOT NULL,
    [DbtrLupdMd]     DATETIME NOT NULL,
    [DbtrLupdMt]     DATETIME NOT NULL,
    [DbtrLupdCk]     INT      NOT NULL,
    [DbtrLupdCb]     INT      NOT NULL,
    [DbtrLupdCs]     SMALLINT NOT NULL,
    [DbtrLupdCd]     DATETIME NOT NULL,
    [DbtrLupdCt]     DATETIME NOT NULL,
    [DbtrTAuthDone]  SMALLINT NOT NULL,
    [DbtrRecStat]    TINYINT  NOT NULL,
    [DbtrAuthDone]   TINYINT  NOT NULL,
    [DbtrAuthNeeded] TINYINT  NOT NULL,
    [DbtrUpdtChkId]  SMALLINT NOT NULL,
    [DbtrLHisTrnNo]  INT      NOT NULL
);

