CREATE TABLE [dbo].[D009043] (
    [LBrCode]           INT        NOT NULL,
    [PrdAcctId]         CHAR (32)  NOT NULL,
    [EffFromDate]       DATETIME   NOT NULL,
    [StartDate]         DATETIME   NOT NULL,
    [IntAccruedTillDT]  FLOAT (53) NOT NULL,
    [ClsDetClosureChrg] FLOAT (53) NOT NULL,
    [ClosureAmtAsOnDT]  FLOAT (53) NOT NULL,
    [WaiveOffAmt]       FLOAT (53) NOT NULL,
    [ClosureAmtPaid]    FLOAT (53) NOT NULL,
    [TotPrinpPaid]      FLOAT (53) NOT NULL,
    [TotInterestPaid]   FLOAT (53) NOT NULL,
    [TotPenalPaid]      FLOAT (53) NOT NULL,
    [TotOthChrgsPaid]   FLOAT (53) NOT NULL,
    [PrinpPaid]         FLOAT (53) NOT NULL,
    [InterestPaid]      FLOAT (53) NOT NULL,
    [PenalPaid]         FLOAT (53) NOT NULL,
    [OthChrgsPaid]      FLOAT (53) NOT NULL,
    [NoOfInsPaid]       INT        NOT NULL,
    [NoOfDefaults]      INT        NOT NULL,
    [PrinpOS]           FLOAT (53) NOT NULL,
    [InterestOS]        FLOAT (53) NOT NULL,
    [PenalOS]           FLOAT (53) NOT NULL,
    [OthChrgsOS]        FLOAT (53) NOT NULL,
    [Remarks]           CHAR (50)  NULL,
    [LnClosureDt]       DATETIME   NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [SetNo]             INT        NOT NULL,
    [ScrollNo]          INT        NOT NULL,
    [MainScrollNo]      INT        NOT NULL,
    [EntryDate]         DATETIME   NOT NULL,
    [BatchCd]           CHAR (8)   NOT NULL,
    [AdjstFrmSD]        CHAR (1)   NOT NULL,
    [PaymntMode]        TINYINT    NOT NULL,
    [BNKACTSRNo]        INT        NOT NULL,
    [ClosedByAcctId]    CHAR (32)  NOT NULL,
    [CollectedBy]       CHAR (8)   NOT NULL,
    [ReceiptNo]         CHAR (12)  NOT NULL,
    [ReceiptDate]       DATETIME   NOT NULL,
    [BatchNumber]       CHAR (20)  NOT NULL,
    [LADemand]          FLOAT (53) NOT NULL,
    [MADemand]          FLOAT (53) NOT NULL,
    [CBUDemand]         FLOAT (53) NOT NULL,
    [CollectedCBU]      FLOAT (53) NOT NULL,
    [PreTerminationFee] FLOAT (53) NOT NULL,
    [SuspBatchCd]       CHAR (8)   NOT NULL,
    [SuspsetNo]         INT        NOT NULL,
    [SuspscrollNo]      INT        NOT NULL,
    [SuspmainScrollNo]  INT        NOT NULL
);

