CREATE TABLE [dbo].[D009243] (
    [LBrCode]           INT        NOT NULL,
    [PrdAcctId]         CHAR (32)  NOT NULL,
    [EffFromDate]       DATETIME   NOT NULL,
    [DisbursedDate]     DATETIME   NOT NULL,
    [InstlStartDate]    DATETIME   NOT NULL,
    [InstlAmt]          FLOAT (53) NOT NULL,
    [InstlIntComp]      FLOAT (53) NOT NULL,
    [LeadsId]           CHAR (16)  NOT NULL,
    [AppliedAsIndvYN]   CHAR (1)   NOT NULL,
    [NewTopUpFlag]      SMALLINT   NOT NULL,
    [SancDate]          DATETIME   NOT NULL,
    [DisbursedAmt]      FLOAT (53) NOT NULL,
    [SDAmt]             FLOAT (53) NOT NULL,
    [RebateAmt]         FLOAT (53) NOT NULL,
    [ChargesAmt]        FLOAT (53) NOT NULL,
    [DisbursedAmtColtd] FLOAT (53) NOT NULL,
    [SDAmtColtd]        FLOAT (53) NOT NULL,
    [RebateAmtColtd]    FLOAT (53) NOT NULL,
    [ChargesAmtColtd]   FLOAT (53) NOT NULL,
    [DisbursedAmtFlag]  TINYINT    NOT NULL,
    [SDAmtFlag]         TINYINT    NOT NULL,
    [RebateAmtFlag]     TINYINT    NOT NULL,
    [ChargesAmtFlag]    TINYINT    NOT NULL,
    [Reason]            CHAR (250) NOT NULL,
    [SetNo]             INT        NOT NULL,
    [ScrollNo]          INT        NOT NULL,
    [EntryDate]         DATETIME   NOT NULL,
    [BatchCd]           CHAR (8)   NOT NULL,
    [MainScrollNo]      INT        NOT NULL,
    [BatchNumber]       CHAR (20)  NOT NULL,
    [Narration]         CHAR (50)  NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [CenterId]          INT        NOT NULL,
    [CRS]               CHAR (8)   NOT NULL,
    [SuspBatchCd]       CHAR (8)   NOT NULL,
    [SuspSetNo]         INT        NOT NULL,
    [SuspScrollNo]      INT        NOT NULL,
    [SuspMainScrollNo]  INT        NOT NULL
);

