CREATE TABLE [dbo].[D009022] (
    [LBrCode]         INT        NOT NULL,
    [PrdAcctId]       CHAR (32)  NOT NULL,
    [NameTitle]       CHAR (4)   NOT NULL,
    [LongName]        CHAR (200) NOT NULL,
    [CurCd]           CHAR (3)   NOT NULL,
    [LedgerNo]        INT        NOT NULL,
    [OpenUser]        CHAR (8)   NULL,
    [DateOpen]        DATETIME   NOT NULL,
    [ClosedUser]      CHAR (8)   NULL,
    [DateClosed]      DATETIME   NOT NULL,
    [AcctType]        TINYINT    NOT NULL,
    [AcctStat]        TINYINT    NOT NULL,
    [MinorType]       TINYINT    NOT NULL,
    [ModeOprn]        TINYINT    NOT NULL,
    [IntOffset]       FLOAT (53) NOT NULL,
    [IntTaxOffset]    FLOAT (53) NOT NULL,
    [PenalOffSet]     FLOAT (53) NOT NULL,
    [FreezeType]      TINYINT    NOT NULL,
    [FrzReasonCd]     TINYINT    NOT NULL,
    [CustNo]          INT        NOT NULL,
    [SplInstr1]       CHAR (60)  NOT NULL,
    [SplInstr2]       CHAR (60)  NOT NULL,
    [DtOfBirth]       DATETIME   NOT NULL,
    [FcyScheme]       CHAR (4)   NOT NULL,
    [InClrgBalFcy]    FLOAT (53) NOT NULL,
    [UnClrEffFcy]     FLOAT (53) NOT NULL,
    [ShdClrBalFcy]    FLOAT (53) NOT NULL,
    [ShdTotBalFcy]    FLOAT (53) NOT NULL,
    [ActClrBalFcy]    FLOAT (53) NOT NULL,
    [ActTotBalFcy]    FLOAT (53) NOT NULL,
    [ActTotBalLcy]    FLOAT (53) NOT NULL,
    [TotalLienFcy]    FLOAT (53) NOT NULL,
    [ChgHoldAmtFcy]   FLOAT (53) NOT NULL,
    [LastDrDate]      DATETIME   NOT NULL,
    [LastCrDate]      DATETIME   NOT NULL,
    [LastCustDrDate]  DATETIME   NOT NULL,
    [LastCustCrDate]  DATETIME   NOT NULL,
    [ChqBookYN]       CHAR (1)   NOT NULL,
    [DpYN]            CHAR (1)   NOT NULL,
    [LastIntAppDate]  DATETIME   NOT NULL,
    [PlrLinkYN]       CHAR (1)   NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [MstrAuthMask]    INT        NOT NULL,
    [FlexiBalance]    FLOAT (53) NOT NULL,
    [FlexiLienBal]    FLOAT (53) NOT NULL,
    [DocFileNo]       CHAR (15)  NOT NULL,
    [FxRevalYN]       CHAR (1)   NOT NULL,
    [Specialcloseoff] CHAR (1)   NOT NULL,
    [Notes]           CHAR (50)  NOT NULL,
    [PropcatCd]       CHAR (4)   NOT NULL,
    [HistcatCd]       CHAR (4)   NOT NULL,
    [BnkCode]         SMALLINT   NOT NULL,
    [BnkAcTypeDesc]   CHAR (50)  NOT NULL,
    [CustAccessCat]   SMALLINT   NOT NULL
);

