CREATE TABLE [dbo].[D009522] (
    [LBrCode]        INT       NOT NULL,
    [PrdAcctId]      CHAR (32) NOT NULL,
    [CustCd]         INT       NOT NULL,
    [PrdCd]          CHAR (8)  NOT NULL,
    [AcctCd1]        INT       NOT NULL,
    [AcctCd2]        INT       NOT NULL,
    [AcctCd3]        INT       NOT NULL,
    [AcctCd4]        INT       NOT NULL,
    [AcctCd5]        INT       NOT NULL,
    [Rem1]           CHAR (50) NOT NULL,
    [Rem2]           CHAR (50) NOT NULL,
    [Rem3]           CHAR (50) NOT NULL,
    [Rem4]           CHAR (50) NOT NULL,
    [Rem5]           CHAR (50) NOT NULL,
    [DbtrAddMk]      INT       NOT NULL,
    [DbtrAddMb]      INT       NOT NULL,
    [DbtrAddMs]      SMALLINT  NOT NULL,
    [DbtrAddMd]      DATETIME  NOT NULL,
    [DbtrAddMt]      DATETIME  NOT NULL,
    [DbtrAddCk]      INT       NOT NULL,
    [DbtrAddCb]      INT       NOT NULL,
    [DbtrAddCs]      SMALLINT  NOT NULL,
    [DbtrAddCd]      DATETIME  NOT NULL,
    [DbtrAddCt]      DATETIME  NOT NULL,
    [DbtrLupdMk]     INT       NOT NULL,
    [DbtrLupdMb]     INT       NOT NULL,
    [DbtrLupdMs]     SMALLINT  NOT NULL,
    [DbtrLupdMd]     DATETIME  NOT NULL,
    [DbtrLupdMt]     DATETIME  NOT NULL,
    [DbtrLupdCk]     INT       NOT NULL,
    [DbtrLupdCb]     INT       NOT NULL,
    [DbtrLupdCs]     SMALLINT  NOT NULL,
    [DbtrLupdCd]     DATETIME  NOT NULL,
    [DbtrLupdCt]     DATETIME  NOT NULL,
    [DbtrTAuthDone]  SMALLINT  NOT NULL,
    [DbtrRecStat]    TINYINT   NOT NULL,
    [DbtrAuthDone]   TINYINT   NOT NULL,
    [DbtrAuthNeeded] TINYINT   NOT NULL,
    [DbtrUpdtChkId]  SMALLINT  NOT NULL,
    [DbtrLHisTrnNo]  INT       NOT NULL
);

