CREATE TABLE [dbo].[D009040] (
    [LBrCode]          INT        NOT NULL,
    [EntryDate]        DATETIME   NOT NULL,
    [BatchCd]          CHAR (8)   NOT NULL,
    [SetNo]            INT        NOT NULL,
    [ScrollNo]         INT        NOT NULL,
    [MainScrollNo]     INT        NOT NULL,
    [PostDate]         DATETIME   NOT NULL,
    [FEffDate]         DATETIME   NOT NULL,
    [ActivityType]     CHAR (8)   NOT NULL,
    [CashFlowType]     CHAR (8)   NOT NULL,
    [ValueDate]        DATETIME   NOT NULL,
    [BookType]         CHAR (2)   NOT NULL,
    [DrCr]             CHAR (1)   NOT NULL,
    [VcrAcctId]        CHAR (32)  NOT NULL,
    [MainAcctId]       CHAR (32)  NOT NULL,
    [MainModType]      SMALLINT   NOT NULL,
    [VcrModType]       SMALLINT   NOT NULL,
    [TrnCurCd]         CHAR (3)   NOT NULL,
    [FcyTrnAmt]        FLOAT (53) NOT NULL,
    [LcyConvRate]      FLOAT (53) NOT NULL,
    [LcyTrnAmt]        FLOAT (53) NOT NULL,
    [InstrBankCd]      SMALLINT   NOT NULL,
    [InstrBranchCd]    SMALLINT   NOT NULL,
    [InstrType]        SMALLINT   NOT NULL,
    [InstrNo]          CHAR (12)  NOT NULL,
    [InstrDate]        DATETIME   NOT NULL,
    [TokenNo]          INT        NOT NULL,
    [Particulars]      CHAR (250) NOT NULL,
    [SysGenVcr]        TINYINT    NOT NULL,
    [ShTotFlag]        CHAR (1)   NOT NULL,
    [ShClrFlag]        CHAR (1)   NOT NULL,
    [AcTotFlag]        CHAR (1)   NOT NULL,
    [AcClrFlag]        CHAR (1)   NOT NULL,
    [Maker]            INT        NOT NULL,
    [MakerDate]        DATETIME   NOT NULL,
    [MakerTime]        INT        NOT NULL,
    [Checker1]         INT        NOT NULL,
    [Checker2]         INT        NOT NULL,
    [Checker3]         INT        NOT NULL,
    [Checker4]         INT        NOT NULL,
    [CheckerDate]      DATETIME   NOT NULL,
    [CheckerTime]      INT        NOT NULL,
    [NoAuthPending]    TINYINT    NOT NULL,
    [NoAuthOver]       TINYINT    NOT NULL,
    [PostFlag]         CHAR (1)   NOT NULL,
    [AuthFlag]         CHAR (1)   NOT NULL,
    [FEffFlag]         CHAR (1)   NOT NULL,
    [CanceledFlag]     CHAR (1)   NOT NULL,
    [PostAuthFeffCncl] TINYINT    NOT NULL,
    [UpdtChkId]        SMALLINT   NOT NULL,
    [PartClearAmt]     FLOAT (53) NOT NULL,
    [PostTime]         INT        NOT NULL,
    [ActCurCd]         CHAR (3)   NOT NULL,
    [ActTrnAmt]        FLOAT (53) NOT NULL,
    [ActConvRate]      FLOAT (53) NOT NULL,
    [OrderId]          CHAR (20)  NOT NULL
);

