CREATE TABLE [dbo].[D009042] (
    [LBrCode]        INT        NOT NULL,
    [PrdAcctId]      CHAR (32)  NOT NULL,
    [EffFromDate]    DATETIME   NOT NULL,
    [CurCd]          CHAR (3)   NOT NULL,
    [PlrLinkYN]      CHAR (1)   NOT NULL,
    [SancAuthority]  CHAR (2)   NOT NULL,
    [SancDate]       DATETIME   NOT NULL,
    [TotSancLimit]   FLOAT (53) NOT NULL,
    [ExpDate]        DATETIME   NOT NULL,
    [Remarks]        CHAR (35)  NOT NULL,
    [EquatedYN]      CHAR (1)   NOT NULL,
    [IntFundedYN]    CHAR (1)   NOT NULL,
    [LnInstFreq]     CHAR (1)   NOT NULL,
    [NoOfInstl]      SMALLINT   NOT NULL,
    [GrcDaysForInst] TINYINT    NOT NULL,
    [GrcDaysForInt]  TINYINT    NOT NULL,
    [FromMnth1]      TINYINT    NOT NULL,
    [NoOfMnth1]      TINYINT    NOT NULL,
    [FromMnth2]      TINYINT    NOT NULL,
    [NoOfMnth2]      TINYINT    NOT NULL,
    [Recom]          CHAR (2)   NOT NULL,
    [ExpLessGrace]   DATETIME   NOT NULL,
    [ReScheduleYN]   CHAR (1)   NOT NULL,
    [DbtrAddMk]      INT        NOT NULL,
    [DbtrAddMb]      INT        NOT NULL,
    [DbtrAddMs]      SMALLINT   NOT NULL,
    [DbtrAddMd]      DATETIME   NOT NULL,
    [DbtrAddMt]      DATETIME   NOT NULL,
    [DbtrAddCk]      INT        NOT NULL,
    [DbtrAddCb]      INT        NOT NULL,
    [DbtrAddCs]      SMALLINT   NOT NULL,
    [DbtrAddCd]      DATETIME   NOT NULL,
    [DbtrAddCt]      DATETIME   NOT NULL,
    [DbtrLupdMk]     INT        NOT NULL,
    [DbtrLupdMb]     INT        NOT NULL,
    [DbtrLupdMs]     SMALLINT   NOT NULL,
    [DbtrLupdMd]     DATETIME   NOT NULL,
    [DbtrLupdMt]     DATETIME   NOT NULL,
    [DbtrLupdCk]     INT        NOT NULL,
    [DbtrLupdCb]     INT        NOT NULL,
    [DbtrLupdCs]     SMALLINT   NOT NULL,
    [DbtrLupdCd]     DATETIME   NOT NULL,
    [DbtrLupdCt]     DATETIME   NOT NULL,
    [DbtrTAuthDone]  SMALLINT   NOT NULL,
    [DbtrRecStat]    TINYINT    NOT NULL,
    [DbtrAuthDone]   TINYINT    NOT NULL,
    [DbtrAuthNeeded] TINYINT    NOT NULL,
    [DbtrUpdtChkId]  SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]  INT        NOT NULL,
    [RecomUsrCd]     CHAR (8)   NOT NULL,
    [SancUsrCd]      CHAR (8)   NOT NULL,
    [OthChgApprop]   FLOAT (53) NOT NULL,
    [InstlAmt]       FLOAT (53) NOT NULL,
    [SrcOfFund]      CHAR (10)  NOT NULL,
    [CDFundedYN]     CHAR (1)   NOT NULL,
    [PreSancLimit]   FLOAT (53) NOT NULL,
    [NewTopUpFlag]   SMALLINT   NOT NULL,
    [LoanCycle]      INT        NOT NULL,
    [BNKACTSRNo]     INT        NOT NULL,
    [InstrNo]        CHAR (8)   NOT NULL,
    [PaymntMode]     TINYINT    NOT NULL,
    [CreditRef]      TINYINT    NOT NULL,
    [SecuritizedYN]  CHAR (4)   NOT NULL,
    [InsuranceYN]    CHAR (1)   NOT NULL,
    [SecuritizorId]  CHAR (20)  NOT NULL
);

