CREATE TABLE [dbo].[D009245] (
    [LBrCode]           INT        NOT NULL,
    [PrdAcctId]         CHAR (32)  NOT NULL,
    [EffFromDate]       DATETIME   NOT NULL,
    [IdealBalDate]      DATETIME   NOT NULL,
    [PrincAmt]          FLOAT (53) NOT NULL,
    [IntAmt]            FLOAT (53) NOT NULL,
    [IdealBal]          FLOAT (53) NOT NULL,
    [CollectedInstAmt]  FLOAT (53) NOT NULL,
    [DueFeesAmt]        FLOAT (53) NOT NULL,
    [CollectedFeesAmt]  FLOAT (53) NOT NULL,
    [FromSDAcctYN]      CHAR (1)   NOT NULL,
    [MemAttandedYN]     CHAR (1)   NOT NULL,
    [PayByGrpYN]        CHAR (1)   NOT NULL,
    [Reason]            CHAR (250) NOT NULL,
    [SetNo]             INT        NOT NULL,
    [ScrollNo]          INT        NOT NULL,
    [MainScrollNo]      INT        NOT NULL,
    [EntryDate]         DATETIME   NOT NULL,
    [BatchCd]           CHAR (8)   NOT NULL,
    [CollFE]            INT        NOT NULL,
    [CumulatvPrincAmt]  FLOAT (53) NOT NULL,
    [CumulatvIntAmt]    FLOAT (53) NOT NULL,
    [AdjFrmExcessActYN] CHAR (1)   NOT NULL,
    [ValueDate]         DATETIME   NOT NULL,
    [BNKACTSRNo]        INT        NOT NULL,
    [ReceiptNo]         CHAR (12)  NOT NULL,
    [ReceiptDate]       DATETIME   NOT NULL,
    [CollectedBy]       CHAR (8)   NOT NULL,
    [BatchNumber]       CHAR (20)  NOT NULL,
    [PaymntMode]        TINYINT    NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [CenterId]          INT        NOT NULL,
    [CRS]               CHAR (8)   NOT NULL,
    [RepAcctId]         CHAR (32)  NOT NULL,
    [MakerTime]         INT        NOT NULL,
    [SuspBatchCd]       CHAR (8)   NOT NULL,
    [SuspsetNo]         INT        NOT NULL,
    [SuspscrollNo]      INT        NOT NULL,
    [SuspmainScrollNo]  INT        NOT NULL,
    [FromSDAmt]         FLOAT (53) NOT NULL
);

