CREATE TABLE [dbo].[D009021] (
    [LBrCode]         INT        NOT NULL,
    [PrdCd]           CHAR (8)   NOT NULL,
    [Name]            CHAR (75)  NOT NULL,
    [CustInt]         CHAR (1)   NOT NULL,
    [ModuleType]      SMALLINT   NOT NULL,
    [AutoGenAcct]     CHAR (1)   NOT NULL,
    [AutoGenSubAcct]  CHAR (1)   NOT NULL,
    [MultiCurYN]      CHAR (1)   NOT NULL,
    [MultiCurAcctYN]  CHAR (1)   NOT NULL,
    [CurCd]           CHAR (3)   NOT NULL,
    [CondAssetGl]     CHAR (8)   NOT NULL,
    [CondLiabGl]      CHAR (8)   NOT NULL,
    [DateOpened]      DATETIME   NOT NULL,
    [DateClosed]      DATETIME   NOT NULL,
    [DateReOpened]    DATETIME   NOT NULL,
    [DateSealed]      DATETIME   NOT NULL,
    [AcctStat]        TINYINT    NOT NULL,
    [AssetLiab]       CHAR (1)   NOT NULL,
    [FinNonFin]       CHAR (1)   NOT NULL,
    [AcctOpenLevel]   CHAR (1)   NOT NULL,
    [ReconType]       CHAR (1)   NOT NULL,
    [ImplDate]        DATETIME   NOT NULL,
    [ImplLevelVP]     CHAR (1)   NOT NULL,
    [LastDrDate]      DATETIME   NOT NULL,
    [LastCrDate]      DATETIME   NOT NULL,
    [MinBal]          FLOAT (53) NOT NULL,
    [MinBalNonChq]    FLOAT (53) NOT NULL,
    [LcyBal]          FLOAT (53) NOT NULL,
    [FcyBal]          FLOAT (53) NOT NULL,
    [CashDrTrnYN]     CHAR (1)   NOT NULL,
    [CashCrTrnYN]     CHAR (1)   NOT NULL,
    [TrfrDrTrnYN]     CHAR (1)   NOT NULL,
    [TrfrCrTrnYN]     CHAR (1)   NOT NULL,
    [ClrgDrTrnYN]     CHAR (1)   NOT NULL,
    [ClrgCrTrnYN]     CHAR (1)   NOT NULL,
    [AccuredYN]       CHAR (1)   NOT NULL,
    [AccuredUpToDate] DATETIME   NOT NULL,
    [AccDebitAcctID]  CHAR (32)  NOT NULL,
    [AccCreditAcctID] CHAR (32)  NOT NULL,
    [AccAmount]       FLOAT (53) NOT NULL,
    [AlmMain]         TINYINT    NOT NULL,
    [AlmSub]          TINYINT    NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [DivisionType]    CHAR (4)   NOT NULL
);

