CREATE TABLE [dbo].[D009039] (
    [LBrCode]         INT        NOT NULL,
    [AcctId]          CHAR (32)  NOT NULL,
    [LastIntAppDate1] DATETIME   NOT NULL,
    [LastIntAppDate2] DATETIME   NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [TotNInt1]        FLOAT (53) NOT NULL,
    [TotAInt1]        FLOAT (53) NOT NULL,
    [TotPInt1]        FLOAT (53) NOT NULL,
    [TotNInt2]        FLOAT (53) NOT NULL,
    [TotAInt2]        FLOAT (53) NOT NULL,
    [TotPInt2]        FLOAT (53) NOT NULL,
    [EntryDate]       DATETIME   NOT NULL,
    [TranCnt]         SMALLINT   NOT NULL
);

