CREATE TABLE [dbo].[D009012] (
    [CustNo]             INT        NOT NULL,
    [NameTitle]          CHAR (4)   NOT NULL,
    [Longname]           CHAR (50)  NOT NULL,
    [DOB]                DATETIME   NOT NULL,
    [DtFromCust]         DATETIME   NOT NULL,
    [Residence]          SMALLINT   NOT NULL,
    [CusType]            SMALLINT   NOT NULL,
    [MaritalStatus]      SMALLINT   NOT NULL,
    [NoOfChildren]       TINYINT    NOT NULL,
    [AnnualIncome]       FLOAT (53) NOT NULL,
    [OtherIncome]        FLOAT (53) NOT NULL,
    [NetWorth]           FLOAT (53) NOT NULL,
    [ValOfInvest]        FLOAT (53) NOT NULL,
    [PanNo]              CHAR (35)  NOT NULL,
    [EducationalQual]    CHAR (15)  NOT NULL,
    [ProfCd]             SMALLINT   NOT NULL,
    [Designation]        CHAR (40)  NOT NULL,
    [OPhone]             CHAR (15)  NOT NULL,
    [PhBanking]          CHAR (1)   NOT NULL,
    [PwdAssigned]        CHAR (1)   NOT NULL,
    [ATMNo]              CHAR (32)  NOT NULL,
    [ValidUpto]          DATETIME   NOT NULL,
    [DesMail]            SMALLINT   NOT NULL,
    [FreqSt]             CHAR (10)  NOT NULL,
    [Decision]           SMALLINT   NOT NULL,
    [Documents]          SMALLINT   NOT NULL,
    [DocumentsDet]       CHAR (100) NOT NULL,
    [IntrCustNo]         INT        NOT NULL,
    [Bank1]              CHAR (6)   NOT NULL,
    [Bank2]              CHAR (6)   NOT NULL,
    [Br1]                CHAR (6)   NOT NULL,
    [Br2]                CHAR (6)   NOT NULL,
    [CreditCards1]       CHAR (20)  NOT NULL,
    [CreditCards2]       CHAR (20)  NOT NULL,
    [Valid1]             DATETIME   NOT NULL,
    [Valid2]             DATETIME   NOT NULL,
    [DebitCard]          CHAR (20)  NOT NULL,
    [CreditCard]         CHAR (20)  NOT NULL,
    [ReligionCd]         SMALLINT   NOT NULL,
    [EmployeeNo]         CHAR (10)  NOT NULL,
    [PassPort]           CHAR (20)  NOT NULL,
    [EmpNameTitle]       CHAR (4)   NOT NULL,
    [EmpLongName]        CHAR (50)  NOT NULL,
    [EmpAddr1]           CHAR (30)  NOT NULL,
    [EmpAddr2]           CHAR (30)  NOT NULL,
    [EmpAddr3]           CHAR (30)  NOT NULL,
    [NoOfService]        SMALLINT   NOT NULL,
    [EmployedWith]       SMALLINT   NOT NULL,
    [CasteCode]          CHAR (4)   NOT NULL,
    [AssetCode]          SMALLINT   NOT NULL,
    [OtherBrAcctCode1]   CHAR (15)  NOT NULL,
    [OtherBrAcctCode2]   CHAR (15)  NOT NULL,
    [CusIDbtrAddMk]      INT        NOT NULL,
    [CusIDbtrAddMb]      INT        NOT NULL,
    [CusIDbtrAddMs]      SMALLINT   NOT NULL,
    [CusIDbtrAddMd]      DATETIME   NOT NULL,
    [CusIDbtrAddMt]      DATETIME   NOT NULL,
    [CusIDbtrAddCk]      INT        NOT NULL,
    [CusIDbtrAddCb]      INT        NOT NULL,
    [CusIDbtrAddCs]      SMALLINT   NOT NULL,
    [CusIDbtrAddCd]      DATETIME   NOT NULL,
    [CusIDbtrAddCt]      DATETIME   NOT NULL,
    [CusIDbtrLupdMk]     INT        NOT NULL,
    [CusIDbtrLupdMb]     INT        NOT NULL,
    [CusIDbtrLupdMs]     SMALLINT   NOT NULL,
    [CusIDbtrLupdMd]     DATETIME   NOT NULL,
    [CusIDbtrLupdMt]     DATETIME   NOT NULL,
    [CusIDbtrLupdCk]     INT        NOT NULL,
    [CusIDbtrLupdCb]     INT        NOT NULL,
    [CusIDbtrLupdCs]     SMALLINT   NOT NULL,
    [CusIDbtrLupdCd]     DATETIME   NOT NULL,
    [CusIDbtrLupdCt]     DATETIME   NOT NULL,
    [CusIDbtrTAuthDone]  SMALLINT   NOT NULL,
    [CusIDbtrRecStat]    TINYINT    NOT NULL,
    [CusIDbtrAuthDone]   TINYINT    NOT NULL,
    [CusIDbtrAuthNeeded] TINYINT    NOT NULL,
    [CusIDbtrUpdtChkId]  SMALLINT   NOT NULL,
    [CusIDbtrLHisTrnNo]  INT        NOT NULL,
    [MemberNo]           INT        NOT NULL,
    [SexCode]            CHAR (2)   NOT NULL,
    [MemberType]         TINYINT    NOT NULL,
    [RetiredDate]        DATETIME   NOT NULL,
    [EmployerCd]         SMALLINT   NOT NULL,
    [Station]            SMALLINT   NOT NULL,
    [RecovThru]          TINYINT    NOT NULL,
    [RelationName]       CHAR (50)  NOT NULL,
    [BldGrp]             CHAR (5)   NOT NULL,
    [ResiStatus]         TINYINT    NOT NULL,
    [RelationType]       CHAR (4)   NOT NULL,
    [RelOffCode]         CHAR (8)   NOT NULL,
    [NoOfMem]            SMALLINT   NOT NULL,
    [LangOfCust]         CHAR (15)  NOT NULL,
    [ExistCustNo]        INT        NOT NULL,
    [ProfileInd]         CHAR (2)   NOT NULL,
    [GroupMtTime]        CHAR (8)   NOT NULL
);

