CREATE TABLE [dbo].[D010004] (
    [LBrCode]         INT        NOT NULL,
    [EntryDate]       DATETIME   NOT NULL,
    [BatchCd]         CHAR (8)   NOT NULL,
    [TotalDrVcrs]     INT        NOT NULL,
    [TotalDrAmtLcy]   FLOAT (53) NOT NULL,
    [TotalCrVcrs]     INT        NOT NULL,
    [TotalCrAmtLcy]   FLOAT (53) NOT NULL,
    [Stat]            TINYINT    NOT NULL,
    [PostDate]        DATETIME   NOT NULL,
    [FeffDate]        DATETIME   NOT NULL,
    [VcEntryMngrType] TINYINT    NOT NULL,
    [AuthFlag]        CHAR (1)   NOT NULL,
    [PostFlag]        CHAR (1)   NOT NULL,
    [FeffFlag]        CHAR (1)   NOT NULL,
    [PostedBy]        INT        NOT NULL,
    [FeffBy]          INT        NOT NULL,
    [InProcFlag]      CHAR (1)   NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [PostingDate]     DATETIME   NOT NULL,
    [PostingTime]     INT        NOT NULL,
    [FundingDate]     DATETIME   NOT NULL,
    [FundingTime]     INT        NOT NULL
);

