CREATE TABLE [dbo].[D010054] (
    [LBrCode]         INT        NOT NULL,
    [PrdAcctId]       CHAR (32)  NOT NULL,
    [AddrType]        TINYINT    NOT NULL,
    [Addr1]           CHAR (50)  NULL,
    [Addr2]           CHAR (50)  NULL,
    [Addr3]           CHAR (35)  NOT NULL,
    [PinCd]           INT        NOT NULL,
    [Tel1]            CHAR (15)  NOT NULL,
    [Tel2]            CHAR (15)  NOT NULL,
    [CityCd]          CHAR (6)   NOT NULL,
    [Fax1]            CHAR (15)  NOT NULL,
    [Fax2]            CHAR (15)  NOT NULL,
    [CountryCd]       CHAR (3)   NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [Area]            INT        NOT NULL,
    [HouseType]       INT        NOT NULL,
    [RntLeasAmt]      FLOAT (53) NOT NULL,
    [RntLeasDep]      FLOAT (53) NOT NULL,
    [ContLeasExp]     DATETIME   NOT NULL,
    [RoofCond]        INT        NOT NULL,
    [Utils]           INT        NOT NULL,
    [AreaType]        INT        NOT NULL,
    [Landmark]        CHAR (80)  NOT NULL,
    [State]           CHAR (3)   NOT NULL,
    [YearStay]        INT        NOT NULL,
    [WardNo]          CHAR (6)   NOT NULL,
    [Mobile]          CHAR (15)  NOT NULL,
    [Email]           CHAR (35)  NOT NULL,
    [PattaName]       CHAR (30)  NOT NULL,
    [Relationship]    CHAR (30)  NOT NULL,
    [SourceOfDep]     TINYINT    NOT NULL,
    [InstAmount]      FLOAT (53) NOT NULL,
    [ToietYN]         CHAR (1)   NOT NULL,
    [NoOfRooms]       INT        NOT NULL,
    [SpouseYearsStay] INT        NOT NULL,
    [DistCd]          INT        NOT NULL,
    [Village]         INT        NOT NULL,
    [CustNo]          INT        NOT NULL,
    [CookFuel]        SMALLINT   NOT NULL,
    [SecMobile]       CHAR (15)  NOT NULL
);

