CREATE TABLE [dbo].[D020004] (
    [LBrCode]         INT        NOT NULL,
    [PrdAcctId]       CHAR (32)  NOT NULL,
    [NameTitle]       CHAR (4)   NOT NULL,
    [LongName]        CHAR (50)  NOT NULL,
    [CurCd]           CHAR (3)   NOT NULL,
    [OffSetRate]      FLOAT (53) NOT NULL,
    [CertDate]        DATETIME   NOT NULL,
    [AsOffdate]       DATETIME   NOT NULL,
    [NoInst]          SMALLINT   NOT NULL,
    [NoOfMonths]      SMALLINT   NOT NULL,
    [NoOfDays]        SMALLINT   NOT NULL,
    [IntRate]         FLOAT (53) NOT NULL,
    [InstOrPrincAmt]  FLOAT (53) NOT NULL,
    [MatVal]          FLOAT (53) NOT NULL,
    [MatDate]         DATETIME   NOT NULL,
    [TotalLien]       FLOAT (53) NOT NULL,
    [PeriodicIntAmt]  FLOAT (53) NOT NULL,
    [BrokenPeriodInt] FLOAT (53) NOT NULL,
    [ReceiptStatus]   TINYINT    NOT NULL,
    [TrfrAcctId]      CHAR (32)  NOT NULL,
    [IntPayableType]  CHAR (1)   NOT NULL,
    [NoOfUnits]       INT        NOT NULL,
    [NoOfRenewals]    SMALLINT   NOT NULL,
    [LastRepayDate]   DATETIME   NOT NULL,
    [MonthsDelay]     SMALLINT   NOT NULL,
    [ClIntPaidAmt]    FLOAT (53) NOT NULL,
    [ClIntRate]       FLOAT (53) NOT NULL,
    [ClNotionalRate]  FLOAT (53) NOT NULL,
    [NoCertPrint]     TINYINT    NOT NULL,
    [MaskRecieptNo]   CHAR (10)  NOT NULL,
    [PrnSrNo]         INT        NOT NULL,
    [ClosedDate]      DATETIME   NOT NULL,
    [Remarks]         CHAR (50)  NOT NULL,
    [InClBalFcy]      FLOAT (53) NOT NULL,
    [UnClBalFcy]      FLOAT (53) NOT NULL,
    [MainBalFcy]      FLOAT (53) NOT NULL,
    [IntPrvdAmtFcy]   FLOAT (53) NOT NULL,
    [IntPaidAmtFcy]   FLOAT (53) NOT NULL,
    [TdsAmtFcy]       FLOAT (53) NOT NULL,
    [MainBalLcy]      FLOAT (53) NOT NULL,
    [IntPrvdAmtLcy]   FLOAT (53) NOT NULL,
    [IntPaidAmtLcy]   FLOAT (53) NOT NULL,
    [TdsAmtLcy]       FLOAT (53) NOT NULL,
    [TdsYN]           CHAR (1)   NOT NULL,
    [TdsReasonCd]     SMALLINT   NOT NULL,
    [AccPrvdAmtFcy]   FLOAT (53) NOT NULL,
    [AccPrvdAmtLcy]   FLOAT (53) NOT NULL,
    [NoticeType]      TINYINT    NOT NULL,
    [SourceOfFunds]   TINYINT    NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [TrfrLBrCode]     INT        NOT NULL,
    [LastAmtPaid]     FLOAT (53) NOT NULL,
    [TotAmtPaid]      FLOAT (53) NOT NULL,
    [LastUnitPaidDt]  DATETIME   NOT NULL,
    [LockPeriod]      SMALLINT   NOT NULL,
    [IntPayPer]       FLOAT (53) NOT NULL,
    [IntPayFreq]      CHAR (1)   NOT NULL,
    [LockEndDate]     DATETIME   NOT NULL,
    [IntPayAmt]       FLOAT (53) NOT NULL,
    [NextPayOutDt]    DATETIME   NOT NULL,
    [LastPayOutDate]  DATETIME   NOT NULL,
    [ModeOfDeposit]   CHAR (20)  NOT NULL
);

