CREATE TABLE [dbo].[D030011] (
    [LBrCode]           INT        NOT NULL,
    [PrdAcctId]         CHAR (32)  NOT NULL,
    [TotSancLimit]      FLOAT (53) NOT NULL,
    [PrioritySecYN]     CHAR (1)   NOT NULL,
    [PrioritySecCat]    INT        NOT NULL,
    [WeakerSecYN]       CHAR (1)   NOT NULL,
    [WeakerSecCat]      INT        NOT NULL,
    [LoanTermCd]        INT        NOT NULL,
    [AssetCd]           INT        NOT NULL,
    [BorrowerCd]        INT        NOT NULL,
    [PurposeCd]         INT        NOT NULL,
    [SubPurposeCd]      INT        NOT NULL,
    [HealthCd]          INT        NOT NULL,
    [PfuSecured]        CHAR (1)   NOT NULL,
    [BSROrgCd]          TINYINT    NOT NULL,
    [ActCd]             TINYINT    NOT NULL,
    [SubActCd]          TINYINT    NOT NULL,
    [SubSubActCd]       TINYINT    NOT NULL,
    [SpCd]              TINYINT    NOT NULL,
    [NatOfAct]          CHAR (20)  NOT NULL,
    [CGCCd]             TINYINT    NOT NULL,
    [CrRiskCd]          TINYINT    NOT NULL,
    [CrRatingCd]        TINYINT    NOT NULL,
    [SecurityCd]        INT        NOT NULL,
    [ValOfSecurity]     FLOAT (53) NOT NULL,
    [RenewalDt]         DATETIME   NOT NULL,
    [GovtProgYN]        CHAR (1)   NOT NULL,
    [GovtProgCd]        TINYINT    NOT NULL,
    [MinCommYN]         CHAR (1)   NOT NULL,
    [MinCommCd]         TINYINT    NOT NULL,
    [AgriYN]            CHAR (1)   NOT NULL,
    [AgriCd]            TINYINT    NOT NULL,
    [CgcCode]           SMALLINT   NOT NULL,
    [SancLetter]        CHAR (30)  NOT NULL,
    [FileNo]            CHAR (30)  NOT NULL,
    [SancDate]          DATETIME   NOT NULL,
    [SancAuth]          CHAR (2)   NOT NULL,
    [CustAcctId]        CHAR (32)  NOT NULL,
    [Document]          CHAR (1)   NOT NULL,
    [BranchInt]         FLOAT (53) NOT NULL,
    [TwentyPntPrgYN]    CHAR (1)   NOT NULL,
    [TwentyPntPrgCd]    TINYINT    NOT NULL,
    [SubsidyElYN]       CHAR (1)   NOT NULL,
    [SubsidyElAmt]      FLOAT (53) NOT NULL,
    [Npadate]           DATETIME   NOT NULL,
    [NPAProvAmt]        FLOAT (53) NOT NULL,
    [IndustryType]      INT        NOT NULL,
    [IndustrySubType]   INT        NOT NULL,
    [AdvocateCd]        INT        NOT NULL,
    [SuitFileDt]        DATETIME   NOT NULL,
    [Caseref]           CHAR (30)  NOT NULL,
    [SuitDecreeDt]      DATETIME   NOT NULL,
    [PlainAmt]          FLOAT (53) NOT NULL,
    [AwardAmt]          FLOAT (53) NOT NULL,
    [Awardstatus]       SMALLINT   NOT NULL,
    [DistCode]          SMALLINT   NOT NULL,
    [PoplnGrp]          TINYINT    NOT NULL,
    [AcctType]          TINYINT    NOT NULL,
    [AcctNature]        TINYINT    NOT NULL,
    [Sec58YN]           CHAR (1)   NOT NULL,
    [ProcChgYN]         CHAR (1)   NOT NULL,
    [SubsidyYN]         CHAR (1)   NOT NULL,
    [SubsidyAmt]        FLOAT (53) NOT NULL,
    [SubClaimDt]        DATETIME   NOT NULL,
    [SubRecevDt]        DATETIME   NOT NULL,
    [SubCreditDt]       DATETIME   NOT NULL,
    [SubsidyInTD]       FLOAT (53) NOT NULL,
    [Sectorcode]        INT        NOT NULL,
    [SubSectorcode]     INT        NOT NULL,
    [Facility]          INT        NOT NULL,
    [Scheme]            INT        NOT NULL,
    [SubScheme]         INT        NOT NULL,
    [Category]          INT        NOT NULL,
    [OverDueSinceDt]    DATETIME   NOT NULL,
    [NPAFreq]           CHAR (1)   NOT NULL,
    [NpaReasonCd]       SMALLINT   NOT NULL,
    [NpaRemarks]        CHAR (45)  NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [ProposalNo]        CHAR (20)  NOT NULL,
    [ProposalDt]        DATETIME   NOT NULL,
    [NonPriorityCat]    INT        NOT NULL,
    [SynSubCode]        SMALLINT   NOT NULL,
    [SynBSROrgCd]       SMALLINT   NOT NULL,
    [SynActCd]          SMALLINT   NOT NULL,
    [SynSubActCd]       SMALLINT   NOT NULL,
    [SynSubSubActCd]    SMALLINT   NOT NULL,
    [SynSpCd]           SMALLINT   NOT NULL,
    [SynCGCCd]          SMALLINT   NOT NULL,
    [SynCrRiskCd]       SMALLINT   NOT NULL,
    [SynCrRatingCd]     SMALLINT   NOT NULL,
    [SynTwentyPntPrgCd] SMALLINT   NOT NULL,
    [SynAgriCd]         SMALLINT   NOT NULL,
    [SynGovtProgCd]     SMALLINT   NOT NULL,
    [SynMinCommCd]      SMALLINT   NOT NULL,
    [LBrCrClsCd1]       CHAR (1)   NOT NULL,
    [LBrCrClsCd2]       CHAR (1)   NOT NULL,
    [LBrCrClsCd3]       CHAR (1)   NOT NULL,
    [LBrCrClsCd4]       CHAR (1)   NOT NULL,
    [FreshBorrowerYN]   CHAR (1)   NOT NULL,
    [NpaPenToDt]        DATETIME   NOT NULL,
    [NpaIdntyDt]        DATETIME   NOT NULL,
    [TrgtCustYn]        CHAR (1)   NOT NULL,
    [DirIndirAdv]       CHAR (1)   NOT NULL,
    [AssetType]         TINYINT    NOT NULL,
    [AssetDesc]         CHAR (35)  NOT NULL,
    [AssetLocn1]        CHAR (35)  NOT NULL,
    [AssetLocn2]        CHAR (35)  NOT NULL,
    [AssetPurchFrom]    CHAR (35)  NOT NULL,
    [PurchDate]         DATETIME   NOT NULL,
    [MarkAsNpa]         CHAR (2)   NOT NULL,
    [NpaReason]         CHAR (50)  NOT NULL
);

