CREATE TABLE [dbo].[D030003] (
    [LBrCode]         INT        NOT NULL,
    [PrdAcctId]       CHAR (32)  NOT NULL,
    [InClrgFcy]       FLOAT (53) NOT NULL,
    [UnClearFcy]      FLOAT (53) NOT NULL,
    [MainBalFcy]      FLOAT (53) NOT NULL,
    [IntPrvdFcy]      FLOAT (53) NOT NULL,
    [IntPaidFcy]      FLOAT (53) NOT NULL,
    [OthChgPrvdFcy]   FLOAT (53) NOT NULL,
    [OthChgPaidFcy]   FLOAT (53) NOT NULL,
    [PenalPrvdFcy]    FLOAT (53) NOT NULL,
    [PenalPaidFcy]    FLOAT (53) NOT NULL,
    [TaxPrvdFcy]      FLOAT (53) NOT NULL,
    [TaxPaidFcy]      FLOAT (53) NOT NULL,
    [DisbursedAmtFcy] FLOAT (53) NOT NULL,
    [MainBalLcy]      FLOAT (53) NOT NULL,
    [IntLcy]          FLOAT (53) NOT NULL,
    [OthChgLcy]       FLOAT (53) NOT NULL,
    [PenalLcy]        FLOAT (53) NOT NULL,
    [TaxLcy]          FLOAT (53) NOT NULL,
    [DisbursedAmtLcy] FLOAT (53) NOT NULL,
    [DbtrAddMk]       INT        NOT NULL,
    [DbtrAddMb]       INT        NOT NULL,
    [DbtrAddMs]       SMALLINT   NOT NULL,
    [DbtrAddMd]       DATETIME   NOT NULL,
    [DbtrAddMt]       DATETIME   NOT NULL,
    [DbtrAddCk]       INT        NOT NULL,
    [DbtrAddCb]       INT        NOT NULL,
    [DbtrAddCs]       SMALLINT   NOT NULL,
    [DbtrAddCd]       DATETIME   NOT NULL,
    [DbtrAddCt]       DATETIME   NOT NULL,
    [DbtrLupdMk]      INT        NOT NULL,
    [DbtrLupdMb]      INT        NOT NULL,
    [DbtrLupdMs]      SMALLINT   NOT NULL,
    [DbtrLupdMd]      DATETIME   NOT NULL,
    [DbtrLupdMt]      DATETIME   NOT NULL,
    [DbtrLupdCk]      INT        NOT NULL,
    [DbtrLupdCb]      INT        NOT NULL,
    [DbtrLupdCs]      SMALLINT   NOT NULL,
    [DbtrLupdCd]      DATETIME   NOT NULL,
    [DbtrLupdCt]      DATETIME   NOT NULL,
    [DbtrTAuthDone]   SMALLINT   NOT NULL,
    [DbtrRecStat]     TINYINT    NOT NULL,
    [DbtrAuthDone]    TINYINT    NOT NULL,
    [DbtrAuthNeeded]  TINYINT    NOT NULL,
    [DbtrUpdtChkId]   SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]   INT        NOT NULL,
    [TotalCredit]     FLOAT (53) NOT NULL,
    [ExcessCredit]    FLOAT (53) NOT NULL,
    [Reserve2]        FLOAT (53) NOT NULL,
    [LastPaydate]     DATETIME   NOT NULL,
    [LastAccrdate]    DATETIME   NOT NULL
);

