CREATE TABLE [dbo].[D045057] (
    [LEADSID]           CHAR (16)  NOT NULL,
    [EffDt]             DATETIME   NOT NULL,
    [AppldLoanAmt]      FLOAT (53) NOT NULL,
    [ApprsdLoanAmt]     FLOAT (53) NOT NULL,
    [Period]            INT        NOT NULL,
    [ExpDt]             DATETIME   NOT NULL,
    [IntRate]           FLOAT (53) NOT NULL,
    [Frequency]         CHAR (1)   NOT NULL,
    [Margin]            FLOAT (53) NOT NULL,
    [InstAmt]           FLOAT (53) NOT NULL,
    [InstStrtDt]        DATETIME   NOT NULL,
    [MonthlyPay]        FLOAT (53) NOT NULL,
    [YearlyPay]         FLOAT (53) NOT NULL,
    [OneTimePay]        FLOAT (53) NOT NULL,
    [LoanBookDt]        DATETIME   NOT NULL,
    [LoanDisbDt]        DATETIME   NOT NULL,
    [LoanAccNum]        CHAR (35)  NOT NULL,
    [LoanAmtDisbd]      FLOAT (53) NOT NULL,
    [AppldLoanAmtCurr]  CHAR (3)   NOT NULL,
    [ApprsdLoanAmtCurr] CHAR (3)   NOT NULL,
    [MarginCurr]        CHAR (3)   NOT NULL,
    [InstAmtCurr]       CHAR (3)   NOT NULL,
    [MonthlyPayCurr]    CHAR (3)   NOT NULL,
    [YearlyPayCurr]     CHAR (3)   NOT NULL,
    [OneTimePayCurr]    CHAR (3)   NOT NULL,
    [LoanAmtDisbdCurr]  CHAR (3)   NOT NULL,
    [ApprvdLoanAmt]     FLOAT (53) NOT NULL,
    [ApprvdLoanAmtCurr] CHAR (3)   NOT NULL,
    [ApplRefNo]         CHAR (20)  NOT NULL,
    [HldyType]          INT        NOT NULL,
    [PortCustNo]        INT        NOT NULL,
    [RepaymentMode]     INT        NOT NULL,
    [PrdCd]             CHAR (8)   NOT NULL,
    [AdvPaymentNo]      INT        NOT NULL,
    [DbtrAddMk]         INT        NOT NULL,
    [DbtrAddMb]         INT        NOT NULL,
    [DbtrAddMs]         SMALLINT   NOT NULL,
    [DbtrAddMd]         DATETIME   NOT NULL,
    [DbtrAddMt]         DATETIME   NOT NULL,
    [DbtrAddCk]         INT        NOT NULL,
    [DbtrAddCb]         INT        NOT NULL,
    [DbtrAddCs]         SMALLINT   NOT NULL,
    [DbtrAddCd]         DATETIME   NOT NULL,
    [DbtrAddCt]         DATETIME   NOT NULL,
    [DbtrLupdMk]        INT        NOT NULL,
    [DbtrLupdMb]        INT        NOT NULL,
    [DbtrLupdMs]        SMALLINT   NOT NULL,
    [DbtrLupdMd]        DATETIME   NOT NULL,
    [DbtrLupdMt]        DATETIME   NOT NULL,
    [DbtrLupdCk]        INT        NOT NULL,
    [DbtrLupdCb]        INT        NOT NULL,
    [DbtrLupdCs]        SMALLINT   NOT NULL,
    [DbtrLupdCd]        DATETIME   NOT NULL,
    [DbtrLupdCt]        DATETIME   NOT NULL,
    [DbtrTAuthDone]     SMALLINT   NOT NULL,
    [DbtrRecStat]       TINYINT    NOT NULL,
    [DbtrAuthDone]      TINYINT    NOT NULL,
    [DbtrAuthNeeded]    TINYINT    NOT NULL,
    [DbtrUpdtChkId]     SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]     INT        NOT NULL,
    [CDFundedYN]        CHAR (1)   NOT NULL,
    [EffLoanAmt]        FLOAT (53) NOT NULL,
    [SrcOfFund]         CHAR (10)  NOT NULL,
    [UsrCd]             CHAR (8)   NOT NULL,
    [Remarks]           CHAR (100) NOT NULL,
    [Moratorium]        INT        NOT NULL,
    [ArrngCommFees]     FLOAT (53) NOT NULL,
    [RepaymentSrc]      CHAR (1)   NOT NULL,
    [PLRLinkYN]         CHAR (1)   NOT NULL,
    [DPYN]              CHAR (1)   NOT NULL,
    [SancAuthority]     CHAR (2)   NOT NULL,
    [RecomAuthority]    CHAR (2)   NOT NULL,
    [PostPrcFees]       FLOAT (53) NOT NULL,
    [PrePrcRecDt]       DATETIME   NOT NULL,
    [PrcsFeeStatus]     INT        NOT NULL,
    [TemplateId]        CHAR (8)   NOT NULL,
    [PaymntMode]        TINYINT    NOT NULL,
    [LoanUsedBy1]       INT        NOT NULL,
    [LoanUsedBy2]       INT        NOT NULL,
    [CreditRef]         TINYINT    NOT NULL,
    [LoanCycle]         INT        NOT NULL,
    [InsuranceYN]       CHAR (1)   NOT NULL,
    [TrancheDetailYN]   CHAR (1)   NOT NULL,
    [ManualY]           CHAR (1)   NOT NULL,
    [GracePerInMnths]   INT        NOT NULL,
    [GracePerInDays]    INT        NOT NULL,
    [NotarialChg]       FLOAT (53) NOT NULL,
    [EncumbaranceChg]   FLOAT (53) NOT NULL,
    [PCICChg]           FLOAT (53) NOT NULL,
    [FarmChg]           FLOAT (53) NOT NULL,
    [SDCollectionFrq]   CHAR (1)   NOT NULL,
    [CollectionMode]    TINYINT    NOT NULL,
    [Cashcardchgs]      FLOAT (53) NOT NULL,
    [Otherchgs]         FLOAT (53) NOT NULL,
    [NominalAcctOthChg] CHAR (32)  NOT NULL,
    [PMPurposeofLoan]   INT        NOT NULL,
    [LoanAgainstFDYN]   CHAR (1)   NOT NULL,
    [FDAcctLBrCode]     INT        NOT NULL,
    [FDAcctId]          CHAR (32)  NOT NULL
);

