CREATE TABLE [dbo].[D045272] (
    [LeadsId]                CHAR (16)  NOT NULL,
    [Loanamt]                FLOAT (53) NOT NULL,
    [Tenor]                  INT        NOT NULL,
    [Emi]                    FLOAT (53) NOT NULL,
    [TotLiqAssets]           FLOAT (53) NOT NULL,
    [TotReceive]             FLOAT (53) NOT NULL,
    [PayInAdv]               FLOAT (53) NOT NULL,
    [TotInvBisns]            FLOAT (53) NOT NULL,
    [TotFixdAssetBisns]      FLOAT (53) NOT NULL,
    [TotBisnsAssets]         FLOAT (53) NOT NULL,
    [TotHsldAssets]          FLOAT (53) NOT NULL,
    [AcctsPayabale]          FLOAT (53) NOT NULL,
    [BisnsDebts]             FLOAT (53) NOT NULL,
    [TotBisnsLiab]           FLOAT (53) NOT NULL,
    [BisnsEquity]            FLOAT (53) NOT NULL,
    [TotHsldLiab]            FLOAT (53) NOT NULL,
    [HsldEquity]             FLOAT (53) NOT NULL,
    [CashSales]              FLOAT (53) NOT NULL,
    [RecovCreditSales]       FLOAT (53) NOT NULL,
    [CostSaleProd]           FLOAT (53) NOT NULL,
    [OperatingCost]          FLOAT (53) NOT NULL,
    [NetBisnsIncom]          FLOAT (53) NOT NULL,
    [OthrIncom]              FLOAT (53) NOT NULL,
    [TotFamExpense]          FLOAT (53) NOT NULL,
    [PaymntTowDebts]         FLOAT (53) NOT NULL,
    [PaymntTowSav]           FLOAT (53) NOT NULL,
    [TotFamIncom]            FLOAT (53) NOT NULL,
    [DisposableIncom]        FLOAT (53) NOT NULL,
    [AmtOfLnInstl]           FLOAT (53) NOT NULL,
    [AvlblSurplus]           FLOAT (53) NOT NULL,
    [InvntryTurnOver]        FLOAT (53) NOT NULL,
    [GrossMargin]            FLOAT (53) NOT NULL,
    [Indebtedness]           FLOAT (53) NOT NULL,
    [IndebtednessWithPropLn] FLOAT (53) NOT NULL,
    [Roe]                    FLOAT (53) NOT NULL,
    [RpymntCap]              FLOAT (53) NOT NULL,
    [TotGradeAcomplish]      FLOAT (53) NOT NULL,
    [DtOfCreditDecision]     DATETIME   NOT NULL,
    [CreditDecision]         CHAR (3)   NOT NULL,
    [LnAmtApproved]          FLOAT (53) NOT NULL,
    [Reason1]                CHAR (3)   NOT NULL,
    [Reason2]                CHAR (3)   NOT NULL,
    [Reason3]                CHAR (3)   NOT NULL,
    [Reason4]                CHAR (3)   NOT NULL,
    [Reason5]                CHAR (3)   NOT NULL
);

