CREATE TABLE [dbo].[D045011] (
    [LeadsId]        CHAR (16)  NOT NULL,
    [ExtCust]        CHAR (3)   NOT NULL,
    [CustNo]         INT        NOT NULL,
    [GrpLeadsId]     INT        NOT NULL,
    [OwnerUsrCd]     CHAR (8)   NOT NULL,
    [Source]         INT        NOT NULL,
    [CampId]         INT        NOT NULL,
    [Name]           CHAR (255) NOT NULL,
    [LeadTypeId]     INT        NOT NULL,
    [LeadSubTypeId]  INT        NOT NULL,
    [Add1]           CHAR (35)  NOT NULL,
    [Add2]           CHAR (35)  NOT NULL,
    [Add3]           CHAR (35)  NOT NULL,
    [AreaCd]         CHAR (6)   NOT NULL,
    [CityCd]         CHAR (6)   NOT NULL,
    [PinCode]        CHAR (10)  NOT NULL,
    [StateCd]        CHAR (3)   NOT NULL,
    [CountryCd]      CHAR (3)   NOT NULL,
    [MobPhone]       CHAR (12)  NOT NULL,
    [HomPhone]       CHAR (50)  NOT NULL,
    [Company]        CHAR (50)  NOT NULL,
    [Desig]          CHAR (50)  NOT NULL,
    [IndustryId]     INT        NOT NULL,
    [BusPhone]       CHAR (50)  NOT NULL,
    [Fax]            CHAR (50)  NOT NULL,
    [Email]          CHAR (50)  NOT NULL,
    [URL]            CHAR (50)  NOT NULL,
    [EmpStrenth]     INT        NOT NULL,
    [AnnCurrCd]      CHAR (3)   NOT NULL,
    [AnnAmt]         FLOAT (53) NOT NULL,
    [GrsCurrCd]      CHAR (3)   NOT NULL,
    [GrsAmt]         FLOAT (53) NOT NULL,
    [DebtCurrCd]     CHAR (3)   NOT NULL,
    [DebtAmt]        FLOAT (53) NOT NULL,
    [PrdTypeId]      INT        NOT NULL,
    [LbrCode]        INT        NOT NULL,
    [PrdCd]          CHAR (8)   NOT NULL,
    [LeadStageId]    INT        NOT NULL,
    [StatusId]       INT        NOT NULL,
    [DisqlfyRmrks]   CHAR (100) NOT NULL,
    [AgentId]        INT        NOT NULL,
    [PrefrdRA]       CHAR (8)   NOT NULL,
    [Flag]           CHAR (1)   NOT NULL,
    [Priority]       INT        NOT NULL,
    [Remarks]        CHAR (150) NOT NULL,
    [UploadId]       INT        NOT NULL,
    [LoyaltyNo]      CHAR (16)  NOT NULL,
    [ApplRefNo]      CHAR (50)  NOT NULL,
    [LGrpCode]       CHAR (20)  NOT NULL,
    [MClRefNo]       CHAR (10)  NOT NULL,
    [CommModeId]     INT        NOT NULL,
    [LeadCat]        INT        NOT NULL,
    [MgrUsrCd]       CHAR (8)   NOT NULL,
    [CreatedDt]      DATETIME   NOT NULL,
    [PrmCustRel]     CHAR (50)  NOT NULL,
    [AnnIncCurCd]    CHAR (3)   NOT NULL,
    [AnnIncome]      FLOAT (53) NOT NULL,
    [MthIncCurCd]    CHAR (3)   NOT NULL,
    [MthIncome]      FLOAT (53) NOT NULL,
    [ExstLoan]       CHAR (1)   NOT NULL,
    [EmiCurCd]       CHAR (3)   NOT NULL,
    [EMIAmt]         FLOAT (53) NOT NULL,
    [SrcDet]         CHAR (100) NOT NULL,
    [CreatedByUsr]   CHAR (8)   NOT NULL,
    [CreatedByBr]    INT        NOT NULL,
    [DbtrAddMk]      INT        NOT NULL,
    [DbtrAddMb]      INT        NOT NULL,
    [DbtrAddMs]      SMALLINT   NOT NULL,
    [DbtrAddMd]      DATETIME   NOT NULL,
    [DbtrAddMt]      DATETIME   NOT NULL,
    [DbtrAddCk]      INT        NOT NULL,
    [DbtrAddCb]      INT        NOT NULL,
    [DbtrAddCs]      SMALLINT   NOT NULL,
    [DbtrAddCd]      DATETIME   NOT NULL,
    [DbtrAddCt]      DATETIME   NOT NULL,
    [DbtrLupdMk]     INT        NOT NULL,
    [DbtrLupdMb]     INT        NOT NULL,
    [DbtrLupdMs]     SMALLINT   NOT NULL,
    [DbtrLupdMd]     DATETIME   NOT NULL,
    [DbtrLupdMt]     DATETIME   NOT NULL,
    [DbtrLupdCk]     INT        NOT NULL,
    [DbtrLupdCb]     INT        NOT NULL,
    [DbtrLupdCs]     SMALLINT   NOT NULL,
    [DbtrLupdCd]     DATETIME   NOT NULL,
    [DbtrLupdCt]     DATETIME   NOT NULL,
    [DbtrTAuthDone]  SMALLINT   NOT NULL,
    [DbtrRecStat]    TINYINT    NOT NULL,
    [DbtrAuthDone]   TINYINT    NOT NULL,
    [DbtrAuthNeeded] TINYINT    NOT NULL,
    [DbtrUpdtChkId]  SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]  INT        NOT NULL,
    [PanNo]          TINYINT    NOT NULL,
    [PanNoDesc]      CHAR (20)  NULL,
    [Title]          CHAR (4)   NOT NULL,
    [RelationDet]    CHAR (150) NOT NULL,
    [LeadEmail]      CHAR (50)  NOT NULL,
    [LeadFax]        CHAR (50)  NOT NULL,
    [LeadPropFlg]    CHAR (1)   NOT NULL,
    [BalSheetFlg]    INT        NOT NULL,
    [IncomeFlg]      INT        NOT NULL,
    [AltMobPhone]    CHAR (50)  NOT NULL,
    [BlShtCSType]    INT        NOT NULL,
    [BNKACTSRNo]     INT        NOT NULL,
    [InstrNo]        CHAR (8)   NOT NULL,
    [SecuritizedYN]  CHAR (4)   NOT NULL,
    [UserCD]         CHAR (8)   NOT NULL,
    [AuthFlag]       CHAR (1)   NOT NULL,
    [PreLeadStageId] INT        NOT NULL,
    [CancelDt]       DATETIME   NOT NULL
);

