CREATE TABLE [dbo].[D045016] (
    [LEADSID]         CHAR (16)  NOT NULL,
    [DOB]             DATETIME   NOT NULL,
    [SEXCODE]         CHAR (1)   NOT NULL,
    [MARITALSTATUS]   INT        NOT NULL,
    [SPOUSE]          CHAR (50)  NOT NULL,
    [NATIONALITY]     CHAR (30)  NOT NULL,
    [RESSTATUS]       INT        NOT NULL,
    [NODEPENDENT]     INT        NOT NULL,
    [HIGHEDU]         CHAR (50)  NOT NULL,
    [AREA]            INT        NOT NULL,
    [STAYSINCE]       DATETIME   NOT NULL,
    [RESIDENSE]       INT        NOT NULL,
    [MORTGAGE]        CHAR (1)   NOT NULL,
    [MORTGAGEDET]     CHAR (100) NOT NULL,
    [LOANAMT]         FLOAT (53) NOT NULL,
    [APPLDT]          DATETIME   NOT NULL,
    [APPLREF]         CHAR (20)  NOT NULL,
    [DOCCHK]          INT        NOT NULL,
    [MemberType]      INT        NOT NULL,
    [MemberNo]        CHAR (20)  NOT NULL,
    [PassportNo]      CHAR (20)  NOT NULL,
    [Language]        INT        NOT NULL,
    [DontDisturbYN]   CHAR (1)   NOT NULL,
    [PrfTelNo]        CHAR (50)  NOT NULL,
    [IntrodNm]        CHAR (50)  NOT NULL,
    [IntrodClNo]      CHAR (16)  NOT NULL,
    [Priority]        INT        NOT NULL,
    [RelwithClient]   INT        NOT NULL,
    [LoanPurpose]     INT        NOT NULL,
    [ProfCd]          SMALLINT   NOT NULL,
    [DirRelYN]        CHAR (1)   NOT NULL,
    [DirRelDet]       CHAR (100) NOT NULL,
    [ResidentYN]      CHAR (1)   NOT NULL,
    [KYCLvl]          CHAR (3)   NOT NULL,
    [REGCertNo]       CHAR (20)  NOT NULL,
    [ISICCd4]         CHAR (20)  NOT NULL,
    [ISICCd6]         CHAR (20)  NOT NULL,
    [ApplnType]       INT        NOT NULL,
    [FacilitiesTC]    INT        NOT NULL,
    [IntLFDt]         DATETIME   NOT NULL,
    [NxtIntRevDt]     DATETIME   NOT NULL,
    [NxtRevDt]        DATETIME   NOT NULL,
    [CreditPolicyYN]  CHAR (1)   NOT NULL,
    [CrPolBrCode]     CHAR (3)   NOT NULL,
    [CrPolBrLevel]    INT        NOT NULL,
    [PrdDevDocCmplYN] CHAR (1)   NOT NULL,
    [PrdDevBrCode]    CHAR (3)   NOT NULL,
    [PrddevBrLevel]   INT        NOT NULL,
    [EnvSocRisk]      INT        NOT NULL,
    [BusNature]       INT        NOT NULL,
    [Competition]     INT        NOT NULL,
    [EntryBarriers]   INT        NOT NULL,
    [PGrpCusto]       INT        NOT NULL,
    [PGrpCustNm]      CHAR (50)  NOT NULL,
    [GrpSlsTrnOver]   FLOAT (53) NOT NULL,
    [GrpCntry]        CHAR (3)   NOT NULL,
    [IDCardNo]        CHAR (20)  NOT NULL,
    [PinCertNo]       CHAR (20)  NOT NULL,
    [DrvLicenceNo]    CHAR (20)  NOT NULL,
    [ApplRecvDt]      DATETIME   NOT NULL,
    [StaySinceYrs]    INT        NOT NULL,
    [StaySinceMths]   INT        NOT NULL,
    [CreditiskPerc]   FLOAT (53) NOT NULL,
    [GuarantedAmt]    FLOAT (53) NOT NULL,
    [ApplAmt]         FLOAT (53) NOT NULL,
    [ApplAmtCur]      CHAR (3)   NOT NULL,
    [DirRelation]     INT        NOT NULL,
    [RESOTHER]        CHAR (50)  NOT NULL,
    [MemberYN]        CHAR (1)   NOT NULL,
    [NoOfShare]       INT        NOT NULL,
    [MemberStat]      CHAR (1)   NOT NULL,
    [PaymentMode]     INT        NOT NULL,
    [TypeOfId]        TINYINT    NOT NULL,
    [IdDesc]          CHAR (15)  NOT NULL,
    [CRB]             INT        NOT NULL
);

