CREATE TABLE [dbo].[D045254] (
    [LeadsId]         CHAR (16)  NOT NULL,
    [AddrType]        TINYINT    NOT NULL,
    [Addr1]           CHAR (50)  NULL,
    [Addr2]           CHAR (50)  NULL,
    [Addr3]           CHAR (35)  NOT NULL,
    [PinCd]           INT        NOT NULL,
    [Tel1]            CHAR (15)  NOT NULL,
    [Tel2]            CHAR (15)  NOT NULL,
    [CityCd]          CHAR (6)   NOT NULL,
    [Fax1]            CHAR (15)  NOT NULL,
    [Fax2]            CHAR (15)  NOT NULL,
    [CountryCd]       CHAR (3)   NOT NULL,
    [Area]            INT        NOT NULL,
    [HouseType]       INT        NOT NULL,
    [RntLeasAmt]      FLOAT (53) NOT NULL,
    [RntLeasDep]      FLOAT (53) NOT NULL,
    [ContLeasExp]     DATETIME   NOT NULL,
    [RoofCond]        INT        NOT NULL,
    [Utils]           INT        NOT NULL,
    [AreaType]        INT        NOT NULL,
    [Landmark]        CHAR (80)  NOT NULL,
    [State]           CHAR (3)   NOT NULL,
    [YearStay]        INT        NOT NULL,
    [WardNo]          CHAR (6)   NOT NULL,
    [Mobile]          CHAR (15)  NOT NULL,
    [Email]           CHAR (35)  NOT NULL,
    [PattaName]       CHAR (30)  NOT NULL,
    [Relationship]    SMALLINT   NOT NULL,
    [SourceOfDep]     TINYINT    NOT NULL,
    [InstAmount]      FLOAT (53) NOT NULL,
    [ToietYN]         CHAR (1)   NOT NULL,
    [NoOfRooms]       INT        NOT NULL,
    [SpouseYearsStay] INT        NOT NULL,
    [DistCd]          INT        NOT NULL,
    [Village]         INT        NOT NULL,
    [CookFuel]        SMALLINT   NOT NULL,
    [SecMobile]       CHAR (15)  NOT NULL
);

