CREATE TABLE [dbo].[D990007] (
    [LBrCode]        INT        NOT NULL,
    [EntryDate]      DATETIME   NOT NULL,
    [BatchCd]        CHAR (8)   NOT NULL,
    [SetNo]          INT        NOT NULL,
    [ScrollNo]       INT        NOT NULL,
    [DeptNo]         INT        NOT NULL,
    [PrjCd]          CHAR (20)  NOT NULL,
    [Division]       INT        NOT NULL,
    [EmpID]          INT        NOT NULL,
    [DbtrAddMk]      INT        NOT NULL,
    [DbtrAddMb]      INT        NOT NULL,
    [DbtrAddMs]      SMALLINT   NOT NULL,
    [DbtrAddMd]      DATETIME   NOT NULL,
    [DbtrAddMt]      DATETIME   NOT NULL,
    [DbtrAddCk]      INT        NOT NULL,
    [DbtrAddCb]      INT        NOT NULL,
    [DbtrAddCs]      SMALLINT   NOT NULL,
    [DbtrAddCd]      DATETIME   NOT NULL,
    [DbtrAddCt]      DATETIME   NOT NULL,
    [DbtrLupdMk]     INT        NOT NULL,
    [DbtrLupdMb]     INT        NOT NULL,
    [DbtrLupdMs]     SMALLINT   NOT NULL,
    [DbtrLupdMd]     DATETIME   NOT NULL,
    [DbtrLupdMt]     DATETIME   NOT NULL,
    [DbtrLupdCk]     INT        NOT NULL,
    [DbtrLupdCb]     INT        NOT NULL,
    [DbtrLupdCs]     SMALLINT   NOT NULL,
    [DbtrLupdCd]     DATETIME   NOT NULL,
    [DbtrLupdCt]     DATETIME   NOT NULL,
    [DbtrTAuthDone]  SMALLINT   NOT NULL,
    [DbtrRecStat]    TINYINT    NOT NULL,
    [DbtrAuthDone]   TINYINT    NOT NULL,
    [DbtrAuthNeeded] TINYINT    NOT NULL,
    [DbtrUpdtChkId]  SMALLINT   NOT NULL,
    [DbtrLHisTrnNo]  INT        NOT NULL,
    [CatCd]          INT        NOT NULL,
    [Amt1]           FLOAT (53) NOT NULL,
    [Amt2]           FLOAT (53) NOT NULL,
    [Amt3]           FLOAT (53) NOT NULL,
    [SrNo]           INT        NOT NULL
);

